settings:
  title: 'Status Page'
  url: 'https://status.o16.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 15 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: 1cloud-o16-dev # unique identifier
    name: cloud.o16.dev
    description: 'Cloudreve storage server on OCI Osaka.' # default=empty
    url: 'https://cloud.o16.dev/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: 2reve-o16-dev
    name: reve.o16.dev
    description: 'Cloudreve in docker on OCI Osaka'
    url: 'https://reve.o16.dev/'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: 3ntp-time-o16-dev
    name: 'NTP at LA'
    url: 'https://btla.o16.dev/conashin'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: false
    
  - id: 4n8n
    name: 'n8n workflow'
    url: 'https://n8n.aptzinc.uk/'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: false
